### ISSUE TITLE
RE-BET算法问题

### ISSUE THREAD

**Issue by 9DemonFox** [9DemonFox/simpleLearning#41]
2.RE-BET 请使用附件数据检查一下代码。（train_data.xlsx和test_data.xlsx）

**Comment by motuer97** [comment]
可以运行，结果在[0,1]范围内

**Comment by motuer97** [comment]
@htx07

**Comment by htx07** [comment]
@motuer97 请下载master分支代码，使用我提供的数据进行测试，确保没有问题。
2月1日那版代码，我这边确认运行失败，失败具体原因我忘记了，但是是由于代码的bug导致。

**Comment by htx07** [comment]
@motuer97 如果确定没有问题就忽略。
